apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-init-db
data:
  init-db.sql: |
    {{ .Values.configMap.initScript1 | nindent 4 }}
  init-products.sql: |
    {{ .Values.configMap.initScript2 | nindent 4 }}
